---
- name: Install nginx on {{ ansible_facts.distribution }}
  ansible.builtin.include_tasks: nginx_{{ ansible_os_family | lower }}.yml
  tags: nginx

- name: Create common virtual host folders
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - /etc/nginx/sites-available/
    - /etc/nginx/sites-enabled/
  tags: nginx

- name: Ensure site-enabled is loaded
  become: true
  ansible.builtin.lineinfile:
    state: present
    dest: /etc/nginx/nginx.conf
    regexp: 'include /etc/nginx/sites-enabled/'
    insertafter: '    include /etc/nginx/conf.d/'
    line: '    include /etc/nginx/sites-enabled/*;'
  tags: nginx

- name: Start & Enable nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  tags: nginx
