---
- name: Install nginx on {{ ansible_facts.distribution }}
  include_tasks: nginx_{{ ansible_facts.pkg_mgr }}.yml
  tags: nginx

- name: Create common virtual host folders
  become: yes
  file:
    state: directory
    path: "{{ item }}"
  loop:
    - /etc/nginx/sites-available/
    - /etc/nginx/sites-enabled/
  tags: nginx

- name: Ensure site-enabled is loaded
  become: yes
  lineinfile:
    state: present
    dest: /etc/nginx/nginx.conf
    regexp: 'include /etc/nginx/sites-enabled/'
    insertafter: '    include /etc/nginx/conf.d/'
    line: '    include /etc/nginx/sites-enabled/*;'
  tags: nginx

- name: Start & Enable nginx
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes
  tags: nginx
