- name: Include OS-specific variables  # noqa: ignore-errors
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts.os_family | lower }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.os_family | lower }}.yml"
  ignore_errors: true

- name: auth | Install auth pre-reqs (Debian)  # noqa: name[casing]
  become: true
  ansible.builtin.apt:
    name:
      - apache2-utils
      - "{{ passlib }}"
    state: present
  register: _task
  retries: 5
  delay: 3
  until: _task is succeeded
  when: ansible_facts.os_family == 'Debian'

- name: auth | Install auth pre-reqs (RedHat)  # noqa: name[casing]
  become: true
  ansible.builtin.yum:
    name:
      - httpd-tools
      - "{{ passlib }}"
    state: present
  register: _task
  retries: 5
  delay: 3
  until: _task is succeeded
  when: ansible_facts.os_family == 'RedHat'

# Use pip to install passlib as no python38-passlib yum package available. Still need python3-passlib
# installed as well though from above task
- name: auth | Install pip pre-reqs (RedHat)  # noqa: name[casing]
  become: true
  ansible.builtin.pip:
    name: passlib
    executable: /usr/bin/pip3
    state: present
  when: ansible_facts.os_family == 'RedHat' and ansible_facts.distribution_major_version!='7'

- name: auth | Create htpasswd file  # noqa: name[casing]
  become: true
  community.general.web_infrastructure.htpasswd:
    path: /etc/st2/htpasswd
    name: "{{ st2_auth_username }}"
    password: "{{ st2_auth_password }}"
    owner: st2
    group: st2
    mode: 0600
  notify:
    - restart st2api
    - restart st2stream

- name: auth | Enable authentication  # noqa: name[casing]
  become: true
  community.general.files.ini_file:
    dest: /etc/st2/st2.conf
    section: auth
    option: enable
    value: True
    backup: true
  notify:
    - restart st2api
    - restart st2stream

- name: auth | Create root's CLI configuration directory  # noqa: name[casing]
  become: true
  ansible.builtin.file:
    path: /root/.st2
    state: directory
    owner: root
    group: root
    mode: 0700
  when: st2_save_credentials | bool

- name: auth | Save credentials in CLI configuration file  # noqa: name[casing]
  become: true
  ansible.builtin.blockinfile:
    dest: /root/.st2/config
    create: yes
    mode: 0600
    owner: root
    group: root
    block: |
      [credentials]
      username = {{ st2_auth_username }}
      password = {{ st2_auth_password }}
  when: st2_save_credentials | bool

- name: auth | Setup LDAP  # noqa: name[casing]
  ansible.builtin.include_tasks: auth-ldap.yml
  when: st2_ldap_enable
  tags: st2, auth, ldap

- name: auth | Setup RBAC  # noqa: name[casing]
  ansible.builtin.include_tasks: auth-rbac.yml
  tags: st2, auth, rbac
