---
- name: Create directory to store roles, assignments, and mappings
  become: yes
  file:
    path: "/opt/stackstorm/rbac/{{ item }}"
    recurse: yes
    state: directory
  loop:
    - roles
    - assignments
    - mappings
  when: st2_rbac_enable|bool

- name: Copy defined RBAC roles to /opt/stackstorm/rbac/roles directory
  become: yes
  template:
    src: rbac_roles/roles.yml.j2
    dest: /opt/stackstorm/rbac/roles/{{ item.name }}.yaml
    owner: st2
    group: st2
  loop: "{{ st2_rbac.roles }}"
  when: st2_rbac_enable|bool and st2_rbac.roles is defined
  notify:
    - reload rbac

- name: Copy RBAC assignments to /opt/stackstorm/rbac/assignments directory
  become: yes
  template:
    src: rbac_assignments/assignments.yml.j2
    dest: /opt/stackstorm/rbac/assignments/{{ item.name }}.yaml
    owner: st2
    group: st2
  loop: "{{ st2_rbac.assignments }}"
  when: st2_rbac_enable|bool
  notify:
    - reload rbac

- name: Copy RBAC mappings to /opt/stackstorm/rbac/mappings directory
  become: true
  template:
    src: rbac_mappings/mappings.yml.j2
    dest: /opt/stackstorm/rbac/mappings/{{ item.name }}.yaml
    owner: st2
    group: st2
  loop: "{{ st2_rbac.mappings }}"
  when: st2_rbac_enable|bool
  notify:
    - reload rbac

- name: Enable RBAC in st2 configuration
  become: yes
  ini_file:
    dest: /etc/st2/st2.conf
    section: rbac
    option: enable
    value: True
    backup: yes
  when: st2_rbac_enable|bool
  notify:
    - restart st2api
    - restart st2auth
    - reload rbac

- name: Enable RBAC sync_remote_groups in st2 configuration
  become: true
  ini_file:
    dest: /etc/st2/st2.conf
    section: rbac
    option: sync_remote_groups
    value: True
    backup: yes
  when:
    - st2_rbac_enable|bool
    - st2_rbac.mappings | length > 0
  notify:
    - restart st2api
    - restart st2auth
    - reload rbac

- name: Set RBAC backend to default in st2 configuration
  become: yes
  ini_file:
    dest: /etc/st2/st2.conf
    section: rbac
    option: backend
    value: default
    backup: yes
  when: st2_rbac_enable|bool
  notify:
    - restart st2api
    - restart st2auth

- name: Disable RBAC in st2 configuration
  become: yes
  ini_file:
    dest: /etc/st2/st2.conf
    section: rbac
    option: enable
    value: False
    backup: yes
  when: not st2_rbac_enable|bool
  notify:
    - restart st2api
    - restart st2auth
