---

- meta: flush_handlers
  tags: st2_packs

- name: Get installed st2 packs in json
  command: st2 pack list -j
  changed_when: no
  check_mode: no
  register: _st2_packs_installed
  # become: yes

# This gets the names of the currently installed st2 packs from a json list of dicts
- set_fact:
    st2_packs_installed: "{{ _st2_packs_installed.stdout|from_json|map(attribute='name')|list() }}"

- name: Install st2 packs --python2
  command: st2 pack install "{{ item }}"
  loop: "{{ st2_packs }}"
  when: item not in st2_packs_installed
  # become: yes
