---
galaxy_info:
  description: Install st2chatops
  author: humblearner
  company: StackStorm
  license: Apache 2.0
  min_ansible_version: 2.5
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: EL
      versions:
        - 6
        - 7
  categories:
    - st2
    - devops
    - chatops
    - automation
    - hubot
dependencies:
    - role: nodejs
    - role: st2
