---
- name: Install mongodb on {{ ansible_distribution }}
  include_tasks: mongodb_{{ ansible_pkg_mgr }}.yml
  tags: [databases, mongodb]

- name: Start & Enable mongodb
  become: yes
  service:
    name: mongod
    state: started
    enabled: yes
  tags: [databases, mongodb]
