---
# defaults file for st2web
st2web_revision: 1

# String with custom SSL certificate. If not provided, self-signed certificate will be generated.
st2web_ssl_certificate: null

# String with custom SSL certificate private key. If not provided, self-signed certificate will be generated.
st2web_ssl_certificate_key: null

# String with a custom nginx configuration file to replace st2.conf. If not provided, the default st2.conf will be used.
st2web_nginx_config: null
