---
- name: Install st2
  hosts: all
  environment: "{{ st2_proxy_env | default({}) }}"
  roles:
    - StackStorm.mongodb
    - StackStorm.rabbitmq
    - role: StackStorm.postgresql
      when: not (ansible_facts.os_family == 'RedHat' and ansible_facts.distribution_major_version == '8') and
            not (ansible_facts.distribution == 'Ubuntu' and ansible_facts.distribution_major_version == '18')
    - StackStorm.st2repo
    - StackStorm.st2
    - role: StackStorm.st2mistral
      when: not (ansible_facts.os_family == 'RedHat' and ansible_facts.distribution_major_version == '8') and
            not (ansible_facts.distribution == 'Ubuntu' and ansible_facts.distribution_major_version == '18')
    - StackStorm.nginx
    - StackStorm.st2web
    - StackStorm.nodejs
    - StackStorm.st2chatops
    - StackStorm.st2smoketests
    - role: StackStorm.ewc
      when: ewc_license is defined and ewc_license is not none and ewc_license | length > 0
    - role: StackStorm.ewc_smoketests
      when: ewc_license is defined and ewc_license is not none and ewc_license | length > 0
