---
- name: Install st2
  hosts: all
  roles:
    - mongodb
    - rabbitmq
    - postgresql
    - st2repo
    - st2
    - st2mistral
    - nginx
    - st2web
    - nodejs
    - st2chatops
    - st2smoketests
    - role: ewc
      when: ewc_license is defined and ewc_license is not none
    - role: ewc_smoketests
      when: ewc_license is defined and ewc_license is not none
