---
- name: Install st2
  hosts: all
  roles:
    - mongodb
    - rabbitmq
    - postgresql
    - st2repo
    - st2
    - st2mistral
    - nginx
    - st2web
    - nodejs
    - st2chatops
    - st2smoketests
    - role: bwc
      when: bwc_license is defined and bwc_license is not null
    - role: bwc_smoketests
      when: bwc_license is defined and bwc_license is not null
