---
- name: Install st2
  hosts: all
  environment: "{{ st2_proxy_env | default({}) }}"
  roles:
    - role: StackStorm.mongodb
      mongodb_version: 4.0
      mongodb_apt_keys:
        "3.2": "42F3E95A2C4F08279C4960ADD68FA50FEA312927"
        "3.4": "0C49F3730359A14518585931BC711F9BA15703C6"
        "4.0": "9da31620334bd75d9dcb49f368818c72e52529d4"
    - StackStorm.rabbitmq
    - StackStorm.postgresql
    - StackStorm.st2repo
    - StackStorm.st2
    # - StackStorm.st2mistral
    - StackStorm.nginx
    - StackStorm.st2web
    - StackStorm.nodejs
    - StackStorm.st2chatops
    - StackStorm.st2smoketests
    - role: StackStorm.ewc
      when: ewc_license is defined and ewc_license is not none and ewc_license | length > 0
    - role: StackStorm.ewc_smoketests
      when: ewc_license is defined and ewc_license is not none and ewc_license | length > 0
