---
- name: Install st2
  hosts: all
  roles:
    - StackStorm.mongodb
    - StackStorm.rabbitmq
    - StackStorm.postgresql
    - StackStorm.st2repo
    - StackStorm.st2
    - StackStorm.st2mistral
    - StackStorm.nginx
    - StackStorm.st2web
    - StackStorm.nodejs
    - StackStorm.st2chatops
    - StackStorm.st2smoketests
    - role: StackStorm.ewc
      when: ewc_license is defined and ewc_license is not none and ewc_license | length > 0
    - role: StackStorm.ewc_smoketests
      when: ewc_license is defined and ewc_license is not none and ewc_license | length > 0
