---
# EWC PackageCloud repository to install: enterprise, enterprise-unstable, staging-enterprise, staging-enterprise-unstable.
bwc_repo: "enterprise"
# `present` to install available package, `latest` to get automatic updates, or pin it to numeric version like `2.2.0`.
bwc_version: latest
# used only if 'bwc_version' is numeric
bwc_revision: 1

# EWC license to install EWC enterprise bits
bwc_license: null

# Specify roles and assignments for EWC RBAC.
# Roles are pushed as YML files to /opt/stackstorm/rbac/roles
# Assignments are pushed as YML files to /opt/stackstorm/rbac/assignments/
# The schema for roles and assignments follow the exact schema definition
# define in https://ewc-docs.extremenetworks.com/rbac.html#defining-roles-and-permission-grants
# and https://ewc-docs.extremenetworks.com/rbac.html#defining-user-role-assignments.

bwc_rbac_default_roles: []

bwc_rbac_default_assignments:
  - name: "{{ st2_system_user }}"
    roles:
      - admin

  - name: "{{ st2_auth_username }}"
    roles:
      - system_admin

bwc_rbac:
  roles: "{{ bwc_rbac_default_roles }}"

  assignments: "{{ bwc_rbac_default_assignments }}"


# By specifying a valid configuration for LDAP,
# (See https://ewc-docs.extremenetworks.com/authentication.html#ldap )
# LDAP auth backend is setup for st2 and EWC.
# Note that you just need to provide the backend_kwargs.
bwc_ldap:
  backend_kwargs: {}
