# CircleCI is used only for linter and syntax checks
version: 2
jobs:
  # Run Ansible-lint checks
  ansible-lint:
    docker:
      - image: yokogawa/ansible-lint
    steps:
      - checkout
      - run:
          name: Ansible YAML syntax check
          command: |
            ansible-playbook --syntax-check stackstorm.yml
      - run:
          name: Ansible-lint check
          command: |
            ansible-lint --version
            ansible-lint -x 106,204,208 -v roles/*/*/*.yaml roles/*/*/*.yml stackstorm.yml

  # Run YAML lint checks
  yaml-lint:
    docker:
      - image: sdesbure/yamllint
    steps:
      - checkout
      - run:
          name: YAML lint checks
          command: yamllint .

workflows:
  version: 2
  lint:
    jobs:
      - ansible-lint
      - yaml-lint

experimental:
  notify:
    branches:
      only:
        - master
