- name: Ensure apt-transport-https is installed
  become: yes
  apt:
    name: apt-transport-https
    state: present
  register: _task
  retries: 5
  delay: 3
  until: _task is succeeded
  tags: nodejs

- name: Add nodesource key
  become: yes
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present
  register: _task
  retries: 5
  delay: 3
  until: _task is succeeded
  tags: nodejs

- name: Add nodesource repos debs
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_major_version }}.x {{ ansible_facts.distribution_release }} main"
    state: present
  tags: nodejs

- name: Install nodejs
  become: yes
  apt:
    name: nodejs={{ nodejs_major_version }}.*
    state: present
  register: _task
  retries: 5
  delay: 3
  until: _task is succeeded
  tags: nodejs
