---
- name: Remove RabbitMQ vhosts
  become: yes
  rabbitmq_vhost:
    vhost: "{{ _rmq_vhost }}"
    state: absent
  loop_control:
    loop_var: _rmq_vhost
  with_items: "{{ rabbitmq_absent_vhosts }}"
  tags: rabbitmq

- name: Add RabbitMQ vhosts
  become: yes
  rabbitmq_vhost:
    vhost: "{{ _rmq_vhost }}"
    state: present
  loop_control:
    loop_var: _rmq_vhost
  with_items: "{{ rabbitmq_vhosts }}"
  tags: rabbitmq
