- name: restart st2
  become: yes
  service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ st2_services }}"

- name: reload st2
  become: yes
  command: st2ctl reload --register-all

- name: restart st2actionrunner
  become: yes
  service:
    name: st2actionrunner
    state: restarted

- name: restart st2api
  become: yes
  service:
    name: st2api
    state: restarted

- name: restart st2stream
  become: yes
  service:
    name: st2stream
    state: restarted
