---
- name: Install mongodb on {{ ansible_facts.distribution }}
  include_tasks: mongodb_{{ ansible_facts.pkg_mgr }}.yml
  tags: [databases, mongodb]

- name: Start & Enable mongodb
  become: yes
  service:
    name: mongod
    state: started
    enabled: yes
  tags: [databases, mongodb]

- name: Enable mongodb authentication
  when: mongodb_enable_auth
  include_tasks: mongodb_auth.yml
  tags: [databases, mongodb]
