---
- name: Retrieve variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags: [databases, mongodb]

- name: Install mongodb on {{ ansible_facts.distribution }}
  include_tasks: mongodb_{{ ansible_os_family | lower }}.yml
  tags: [databases, mongodb]

- name: Start & Enable mongodb
  become: yes
  service:
    name: mongod
    state: started
    enabled: yes
  tags: [databases, mongodb]
