FROM stackstorm/packagingtest:rockylinux8-systemd

RUN set -eu \
  && useradd --create-home --user-group {{ item.username }} \
  && echo "{{ item.username }} ALL=(ALL) NOPASSWD: ALL" >/etc/sudoers.d/{{ item.username }}
