---
- name: get authentication token
  command: st2 auth "{{ st2_auth_username }}" -p "{{ st2_auth_password }}" -t
  register: st2_token
  changed_when: no
  tags:
    - pack_install

- name: Get installed st2 packs (in json format)
  command: /usr/bin/st2 pack list -j
  environment:
    ST2_AUTH_TOKEN: "{{ st2_token.stdout }}"
  changed_when: no
  check_mode: no
  register: _st2_packs_installed

# This gets the names of the currently installed st2 packs from a json list of dicts
- set_fact:
    st2_packs_installed: "{{ _st2_packs_installed.stdout|from_json|map(attribute='name')|list() }}"

- name: Install st2 packs --python2
  command: st2 pack install "{{ item }}"
  environment:
    ST2_AUTH_TOKEN: "{{ st2_token.stdout }}"
  loop: "{{ st2_packs }}"
  when: item not in st2_packs_installed

- name: Install st2 packs --python3
  command: st2 pack install "{{ item }}" --python3
  environment:
    ST2_AUTH_TOKEN: "{{ st2_token.stdout }}"
  loop: "{{ st2_packs_py3 }}"
  when: (item not in st2_packs_installed) and
        (install_python_3)