mongo_dependencies:
      - python-urllib3
      - pyOpenSSL
      - python-pyasn1
      - python-ndg_httpsclient
# Set mongodb version to provided value or 3.6 if not specified
mongodb_use_version: "{{ mongodb_version | default (mongodb36_version) }}"
# Extract mongodb "major.minor" version
mongodb_major_minor_version: "{{ (mongodb_use_version|string)[:3] }}"
