mongo_dependencies:
      - python3-urllib3
      - python3-pyOpenSSL
      - python3-pyasn1
# We cannot have conditional defaults. The default for mongodb_version is 3, but
# for RH 8 we want to use version 4 at least. So if mongodb_version is 3 use the
# default mongodb4_version
mongodb_use_version: "{{ (mongodb4_version|string)[:3] if ( mongodb_version|string)[:1] == '3' else (mongodb_version|string)[:3] }}"
# Extract mongodb "major.minor" version
mongodb_major_minor_version: "{{ (mongodb_use_version|string)[:3] }}"
