mongo_dependencies:
      - python-urllib3
      - pyOpenSSL
      - python-pyasn1
      - python-ndg_httpsclient
# Extract mongodb "major.minor" version
mongodb_major_minor_version: "{{ (mongodb_version|string)[:3] }}"
