---
galaxy_info:
  description: Install st2web
  author: humblearner
  company: StackStorm
  license: Apache
  min_ansible_version: 2.5
  tags: st2web
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: EL
      versions:
        - 6
        - 7
  categories:
    - system
dependencies:
  - role: nginx
  - role: st2repo
  - role: st2
