---
- name: Install redis
  become: yes
  package:
    name: redis
    state: present
  register: _task
  retries: 5
  delay: 3
  until: _task is succeeded
  tags: redis

- name: Ensure redis service is enabled and running
  become: yes
  service:
    name: redis
    enabled: yes
    state: started
  tags: redis
