---
- name: Install prereqs (Debian)
  become: yes
  apt:
    name:
      - debian-archive-keyring
      - apt-transport-https
    state: present
  register: _task
  retries: 5
  delay: 3
  until: _task is succeeded
  tags: st2repo

- name: Add keys to keyring
  become: yes
  apt_key:
    id: 418A7F2FB0E1E6E7EABF6FE8C2E73424D59097AB
    url: https://packagecloud.io/StackStorm/{{ st2repo_name }}/gpgkey
    state: present
  register: _task
  retries: 5
  delay: 3
  until: _task is succeeded
  tags: st2repo

- name: Add StackStorm repo
  become: yes
  apt_repository:
    repo: 'deb https://packagecloud.io/StackStorm/{{ st2repo_name }}/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release|lower }} main'
    state: present
    update_cache: yes
  tags: st2repo
