---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  -
    name: ubuntu-20.04
    groups: [test]
    pre_build_image: false
    image: stackstorm/packagingtest:focal-systemd
    dockerfile: Dockerfile.ubuntu20.j2
    privileged: true
    command: /sbin/init
    tmpfs: [/run, /tmp]
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:rw]
    cgroupns_mode: host
    username: molecule
  -
    name: rockylinux-8
    groups: [test]
    pre_build_image: false
    image: stackstorm/packagingtest:rockylinux8-systemd
    privileged: true
    dockerfile: Dockerfile.rockylinux8.j2
    command: /sbin/init
    tmpfs: [/run, /tmp]
    volumes: [/sys/fs/cgroup:/sys/fs/cgroup:rw]
    cgroupns_mode: host
    username: molecule

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  playbooks:
    converge: ../../stackstorm.yml
  inventory:
    group_vars:
      test:
        ansible_user: molecule
        st2_auth_username: testu
        st2_auth_password: testp
        st2chatops_hubot_adapter: slack
        st2chatops_config:
          HUBOT_SLACK_TOKEN: "{{ lookup('ansible.builtin.env', 'HUBOT_SLACK_TOKEN') }}"
        st2_rbac_enable: true

verifier:
  name: ansible

# lint: |
#   set -e
#   yamllint .
#   flake8
#   ansible-lint

scenario:
  create_sequence:
    # - dependency
    - create
    # - prepare
  check_sequence:
    # - dependency
    # - cleanup
    - destroy
    - create
    # - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    # - dependency
    - create
    # - prepare
    - converge
  destroy_sequence:
    # - dependency
    # - cleanup
    - destroy
  test_sequence:
    # - dependency
    # - lint
    # - cleanup
    - destroy
    - syntax
    - create
    # - prepare
    - converge
    - idempotence
    # - side_effect
    # - verify
    # - cleanup
    - destroy
