---
galaxy_info:
  description: Install MongoDB
  author: humblearner
  company: StackStorm
  license: Apache
  min_ansible_version: 2.5
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: EL
      versions:
        - 6
        - 7
  categories:
    - system
dependencies:
  - role: epel
    when: ansible_os_family == 'RedHat'
